# Generated by Django 4.2.7 on 2023-12-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_type',
            new_name='transaction_type',
        ),
    ]
