# Generated by Django 4.2.7 on 2024-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
